version: "3.8"
services:
  app:
    build: .
    container_name: backend-learning-orm
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/learningorm
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
  db:
    image: postgres:15
    container_name: backend-learning-orm-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learningorm
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: